language: cpp
dist: trusty


jobs:
    include:
        - os: linux
          dist: trusty
          env: _DIST=trusty
        - os: linux
          dist: xenial
          env: _DIST=xenial
        #- os: linux
          #dist: bionic
          #env: _DIST=bionic

branches:
    only:
        - master


before_install:
- if [[ "${_DIST}" == trusty ]]; then sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test && sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y && sudo apt-get update -qq ; fi
- if [[ "${_DIST}" == trusty ]]; then echo "this is trusty" ; fi
- if [[ "${_DIST}" == xenial ]]; then echo "this is xenial" ; fi


install:
- sudo apt-get -y install software-properties-common checkinstall xvfb dh-make fakeroot gpgv2 tree g++-8
#- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
- export CC=gcc-8 && export CXX=g++-8
- if [[ "${_DIST}" == trusty ]]; then sudo apt-get install -qq qt510base && source /opt/qt510/bin/qt510-env.sh ; fi
- if [[ "${_DIST}" == xenial ]]; then sudo apt-get install -qq qt5-default qt5-qmake ; fi



before_script:
- qmake -v


script:
- qmake -v
#- make -j$(nproc)


#deploy:
  #provider: releases
  #draft: true
  #edge: true
  #cleanup: true
  #token: $GITHUB_TOKEN
  #file:
   #- mytest
  #file_glob: true
  #on:
    #repo: foufounou/mytest
    #tags: false
