language: cpp
os: linux
dist: trusty

services:
- docker

jobs:
    include:
        - os: linux
          dist: trusty
          env: _DIST=trusty
        #- os: linux
          #dist: xenial
          #env: _DIST=xenial
        #- os: linux
          #dist: bionic
          #env: _DIST=bionic

branches:
    only:
        - master

archlinux:
  packages:
  - qt5-base
  - qt5-tools
  - tree
  mount:
  - ~/.pkg-cache:/var/cache/pacman/pkg
  #before_install:
  #- "sudo ln -s /dev/null /etc/pacman.d/hooks/package-cleanup.hook"
  script:
  - echo "before makepkg" && pwd && tree .
  - "cd packaging && makepkg -s && cd .."
  - echo "after makepkg" && tree .

  
before_install:
- sudo apt-get update -qq


install:
- sudo apt-get install -qq tree

script:
- "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
- pwd && tree .



#deploy:
  #provider: releases
  #draft: true
  #edge: true
  #cleanup: true
  #token: $GITHUB_TOKEN
  #file:
   #- mytest
  #file_glob: true
  #on:
    #repo: foufounou/mytest
    #tags: false
