language: cpp
dist: trusty


jobs:
    include:
        - os: linux
          dist: trusty
          env: _DIST=trusty
        - os: linux
          dist: xenial
          env: _DIST=xenial
        - os: linux
          dist: bionic
          env: _DIST=bionic

branches:
    only:
        - master

before_install:
- if [[ "${TRAVIS_OS_NAME}" == linux ]]; then sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test ; fi
- if [[ "${_DIST}" == trusty ]]; then sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y ; fi
- if [ "${_DIST}" == xenial ] || [ "${_DIST}" == bionic ] ; then sudo add-apt-repository ppa:beineri/opt-qt-5.14.1-$_DIST -y ; fi
- if [[ "${TRAVIS_OS_NAME}" == linux ]]; then sudo apt-get update -qq ; fi


install:
- if [[ "${TRAVIS_OS_NAME}" == linux ]]; then sudo apt-get -y install software-properties-common checkinstall xvfb dh-make fakeroot gpgv2 tree g++-8 ; fi
- if [[ "${TRAVIS_OS_NAME}" == linux ]]; then export CC=gcc-8 && export CXX=g++-8 ; fi
- if [[ "${_DIST}" == trusty ]]; then sudo apt-get install -qq qt510base && source /opt/qt510/bin/qt510-env.sh ; fi
#- if [[ "${_DIST}" == xenial ]]; then sudo apt-get install -qq qt514base && source /opt/qt514/bin/qt514-env.sh ; fi
#- if [[ "${_DIST}" == bionic ]]; then sudo apt-get install -qq qt514base && source /opt/qt514/bin/qt514-env.sh ; fi
- if [ "${_DIST}" == xenial ] || [ "${_DIST}" == bionic ] ; then sudo apt-get install -qq qt514base && source /opt/qt514/bin/qt514-env.sh ; fi



before_script:
- qmake


script:
- make -j$(nproc)


after_success:
- mkdir -p appimage/mytest/usr/bin
- cp mytest appimage/mytest/usr/bin
- cp -t appimage/mytest/ mytest.desktop mytest.png
- wget -c https://github.com/probonopd/linuxdeployqt/releases/download/6/linuxdeployqt-6-x86_64.AppImage
- chmod +x linuxdeployqt-6-x86_64.AppImage
- ./linuxdeployqt-6-x86_64.AppImage -appimage appimage/mytest/usr/bin/mytest
- echo $PWD
- tree .


#deploy:
  #provider: releases
  #draft: true
  #edge: true
  #cleanup: true
  #token: $GITHUB_TOKEN
  #file:
   #- mytest
  #file_glob: true
  #on:
    #repo: foufounou/mytest
    #tags: false
