language: cpp
dist: trusty


jobs:
    include:
        - os: linux
          dist: trusty
          env: _DIST=trusty
        - os: linux
          dist: xenial
          env: _DIST=xenial
        - os: linux
          dist: bionic
          env: _DIST=bionic

branches:
    only:
        - master


before_install:
- echo "------------------------------"
- echo "---------- $_DIST -------------"
#- echo "------ os $TRAVIS_OS_NAME"
#- sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test && 
#- sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y
#- sudo apt-get update -qq



#install:
#- sudo apt-get -y install software-properties-common checkinstall xvfb dh-make fakeroot gpgv2 tree
#- sudo apt-get install -qq g++-8 qt510base
#- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
#- source /opt/qt510/bin/qt510-env.sh



#before_script:
#- qmake -v


#script:
#- make -j$(nproc)


#deploy:
  #provider: releases
  #draft: true
  #edge: true
  #cleanup: true
  #token: $GITHUB_TOKEN
  #file:
   #- mytest
  #file_glob: true
  #on:
    #repo: foufounou/mytest
    #tags: false
